### ISSUE TITLE
Source for the electronics?

### ISSUE THREAD

**Issue by ghost** [Sovol3d/SV06-Fully-Open-Source#2]
Controller, connectors, wiring looms, display (and driver etc), input (buttons you push), storage, communications ports, etc.... 

Schematics and layouts... I can't seem to find these here, am I missing something? Repo is named "fully open source" and marketing says the same, but I don't see any of these things.

**Comment by Sovol3d** [comment]
Sorry we miss that file. We are translating the files and will upload them soon!

**Comment by ghost** [comment]
Your tech support is very impressive. Fast, friendly, helpful. Thank you very much!!
