### ISSUE TITLE
probe z offset issues

### ISSUE THREAD

**Issue by a13xlol** [Sovol3d/SV06-Fully-Open-Source#5]
probe z offset works super rarely and is very buggy please fix

**Comment by Sovol3d** [comment]
Dear Alex,
May I know your order number first?
Regarding the problem you encountered, could you please send us some pictures/videos to show your problem, which will be easier for our engineers to give you support?
Best regards,
Jan
website: sovol3d.com
Follow us to get an exclusive 3D printing information
Sovol Official User Group: https://www.facebook.com/groups/sovol3d <https://www.facebook.com/sovol3d/ >
Facebook Page:https://www.facebook.com/sovol3d <https://twitter.com/Sovol3d >
Youtube: https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog <https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog >
------------------------------------------------------------------
From:alex ***@***.***>
Sent At:2023 Aug. 9 (Wed.) 05:42
To:Sovol3d/SV06-Fully-Open-Source ***@***.***>
Cc:Subscribed ***@***.***>
Subject:Re: [Sovol3d/SV06-Fully-Open-Source] probe z offset issues (Issue #5)
Closed #5 <https://github.com/Sovol3d/SV06-Fully-Open-Source/issues/5 > as completed.
